const assert = require('assert');
const fs = require('fs');
const path = require('path');

const html = fs.readFileSync(path.join(__dirname, '..', 'src', 'compendium.html'), 'utf8');
const js = fs.readFileSync(path.join(__dirname, '..', 'src', 'compendium.js'), 'utf8');
const preload = fs.readFileSync(path.join(__dirname, '..', 'src', 'preload.js'), 'utf8');
const launcher = fs.readFileSync(path.join(__dirname, '..', 'src', 'compendium-launcher.js'), 'utf8');
const dataExpansion = fs.readFileSync(path.join(__dirname, '..', 'src', 'compendium-data-expansion.js'), 'utf8');
const categories = fs.readFileSync(path.join(__dirname, '..', 'src', 'compendium-categories.js'), 'utf8');
const links = fs.readFileSync(path.join(__dirname, '..', 'src', 'compendium-links.js'), 'utf8');
const researchSchema = fs.readFileSync(path.join(__dirname, '..', 'src', 'research-v2-schema.js'), 'utf8');
const researchBatch = fs.readFileSync(path.join(__dirname, '..', 'src', 'research-v2-batch-01.js'), 'utf8');
const researchBatch2 = fs.readFileSync(path.join(__dirname, '..', 'src', 'research-v2-batch-02.js'), 'utf8');
const researchBatch3 = fs.readFileSync(path.join(__dirname, '..', 'src', 'research-v2-batch-03.js'), 'utf8');
const researchBatch4 = fs.readFileSync(path.join(__dirname, '..', 'src', 'research-v2-batch-04.js'), 'utf8');
const researchBatch5 = fs.readFileSync(path.join(__dirname, '..', 'src', 'research-v2-batch-05.js'), 'utf8');
const researchBatch6 = fs.readFileSync(path.join(__dirname, '..', 'src', 'research-v2-batch-06.js'), 'utf8');
const researchBatch7 = fs.readFileSync(path.join(__dirname, '..', 'src', 'research-v2-batch-07.js'), 'utf8');
const researchBatch8 = fs.readFileSync(path.join(__dirname, '..', 'src', 'research-v2-batch-08.js'), 'utf8');
const researchUi = fs.readFileSync(path.join(__dirname, '..', 'src', 'compendium-research-v2.js'), 'utf8');
const researchNotesUi = fs.readFileSync(path.join(__dirname, '..', 'src', 'compendium-research-v2-skill-notes.js'), 'utf8');
new Function(dataExpansion);
new Function(categories);
new Function(links);
new Function(researchSchema);
new Function(researchBatch);
new Function(researchBatch2);
new Function(researchBatch3);
new Function(researchBatch4);
new Function(researchBatch5);
new Function(researchBatch6);
new Function(researchBatch7);
new Function(researchBatch8);
new Function(researchUi);
new Function(researchNotesUi);

assert.match(html, /id="compSearch"/);
assert.match(html, /id="compNav"/);
assert.match(html, /id="compArticle"/);
assert.match(html, /id="compBackButton"/);
assert.match(html, /research-data-6\.js/);
assert.match(html, /research-data-final\.js/);
assert.match(html, /research-v2-schema\.js/);
assert.match(html, /research-v2-batch-01\.js/);
assert.match(html, /research-v2-batch-02\.js/);
assert.match(html, /research-v2-batch-03\.js/);
assert.match(html, /research-v2-batch-04\.js/);
assert.match(html, /research-v2-batch-05\.js/);
assert.match(html, /research-v2-batch-06\.js/);
assert.match(html, /research-v2-batch-07\.js/);
assert.match(html, /research-v2-batch-08\.js/);
assert.match(html, /compendium-research-v2\.js/);
assert.match(html, /compendium-research-v2-skill-notes\.js/);
assert.match(html, /compendium-research-v2\.css/);
assert(html.indexOf('research-v2-schema.js') < html.indexOf('research-v2-batch-01.js'), 'Research schema must load before batch data');
assert(html.indexOf('research-v2-batch-01.js') < html.indexOf('research-v2-batch-02.js'), 'Research batches must load in sequence');
assert(html.indexOf('research-v2-batch-02.js') < html.indexOf('research-v2-batch-03.js'), 'Research batches must load in sequence');
assert(html.indexOf('research-v2-batch-03.js') < html.indexOf('research-v2-batch-04.js'), 'Research batches must load in sequence');
assert(html.indexOf('research-v2-batch-04.js') < html.indexOf('research-v2-batch-05.js'), 'Research batches must load in sequence');
assert(html.indexOf('research-v2-batch-05.js') < html.indexOf('research-v2-batch-06.js'), 'Research batches must load in sequence');
assert(html.indexOf('research-v2-batch-06.js') < html.indexOf('research-v2-batch-07.js'), 'Research batches must load in sequence');
assert(html.indexOf('research-v2-batch-07.js') < html.indexOf('research-v2-batch-08.js'), 'Research batches must load in sequence');
assert(html.indexOf('compendium-research-v2.js') < html.indexOf('compendium-research-v2-skill-notes.js'), 'Skill source notes must wrap the detailed renderer last');
assert(html.indexOf('compendium-links.js') < html.indexOf('compendium-research-v2.js'), 'Detailed renderer must wrap the stable Compendium renderer last');
assert.match(html, /orders-reference-final\.js/);
assert.match(html, /compendium-data-expansion\.js/);
assert.match(html, /compendium-categories\.js/);
assert.match(html, /compendium-links\.js/);
assert.match(html, /compendium-expansion\.css/);
assert.match(js, /Group \$\{group\}/);
assert.match(js, /showSkill/);
assert.match(js, /showEntity/);
assert.match(js, /goBack/);
assert.match(js, /data-entity/);
assert.match(js, /showTopic/);
assert.match(js, /land-combat/);
assert.match(js, /naval-combat/);
assert.match(categories, /Hide research-only items/);
assert.match(categories, /\['skills','Skills'\]/);
assert.match(categories, /\['items','Items'\]/);
assert.match(categories, /\['buildings','Buildings'\]/);
assert.match(categories, /\['ships','Ships'\]/);
assert.match(categories, /showResearch/);
assert.match(categories, /localeCompare/);
assert.match(categories, /comp-skill-table/);
assert.match(categories, /Research-locked/);
assert.match(categories, /Valid Skills index only/);
assert.match(links, /Research topics/);
assert.match(links, /Used as an implement/);
assert.match(links, /Used to make \/ operate/);
assert.match(researchUi, /Research from other skills affecting/);
assert.match(researchUi, /Item specification/);
assert.match(researchUi, /Building specification/);
assert.match(researchUi, /Source gaps/);
assert.match(researchUi, /Source wording \/ inconsistencies/);
assert.match(researchUi, /fully indexed/);
assert.doesNotMatch(researchUi, /fully indexed in Batch 1/);
assert.match(researchSchema, /notesForSkill/);
assert.match(researchNotesUi, /Research status \/ source notes/);
assert.match(researchNotesUi, /Ship specification/);
assert.match(preload, /getCompendiumCatalog/);
assert.match(preload, /compendium-launcher\.js/);
assert.match(launcher, /compendium\.html/);

// Research List baseline is loaded in chunks so it remains maintainable.
global.window = {};
require('../src/research-data.js');
for (let i = 1; i <= 6; i++) require(`../src/research-data-${i}.js`);
require('../src/research-data-final.js');
assert(window.TribeNetResearchData.topics.length >= 250, 'Research List should expose the broad topic catalogue');
assert(window.TribeNetResearchData.extraSkills.some(s => s.name === 'Admiralty'));
assert(window.TribeNetResearchData.topics.some(t => t.name === 'Sling' || /Mining Ladder/i.test(t.name)), 'Research data should include concrete research outputs');

require('../src/orders-reference-data.js');
require('../src/orders-reference-skills.js');
for (let i = 1; i <= 3; i++) require(`../src/orders-reference-goods-${i}.js`);
for (let i = 1; i <= 2; i++) require(`../src/orders-reference-implements-${i}.js`);
require('../src/orders-reference-final.js');
const orders = window.TribeNetOrdersReference;
assert(orders.skills.length >= 100, 'Valid_Skills baseline should include all current workbook skills');
assert(orders.goods.length >= 450, 'Valid Goods baseline should include the current workbook goods list');
assert(orders.implements.length >= 60, 'Valid_Implements baseline should include the current workbook implements');
assert(orders.skills.some(s => s.name === 'Artillery'));
assert(orders.goods.some(g => g.name === 'Longship' && g.table === 'SHIP'));
assert(orders.implements.some(i => i.name === 'Sling' && i.uses.some(u => u.activity === 'HUNTING')));

console.log('Compendium static wiring and baseline tests passed.');
