const assert = require('assert');
const fs = require('fs');

const actions = fs.readFileSync('src/turn-actions.js', 'utf8');
const savedPlans = fs.readFileSync('src/saved-movement-plans.js', 'utf8');
const index = fs.readFileSync('src/index.html', 'utf8');
const mapperStyles = fs.readFileSync('src/movement-planner.css', 'utf8');
const movementPlanner = fs.readFileSync('src/movement-planner.js', 'utf8');
const renderer = fs.readFileSync('src/renderer.js', 'utf8');

assert.match(index, /id="turnActionBar"/, 'The mapper must expose the selected-unit action bar.');
assert.match(index, /id="turnActionHoverCard"/, 'Move Unit must expose a hover cost readout.');
assert.match(index, /id="turnActionTooltip"/, 'Action controls must expose an immediate tooltip surface.');
assert.match(index, /id="scoutRoutesDialog"/, 'Scouting orders must have a dedicated edit dialog.');
assert.match(index, /id="turnActionRouteLegend"/, 'The map must expose a route certainty legend.');
assert.match(index, /id="unitSplitDialog"/, 'Split Off Unit must have a dedicated dialog.');
assert.match(actions, /Move Unit/, 'Move Unit action is missing.');
assert.match(actions, /Split Off Unit/, 'Split Off Unit action is missing.');
assert.match(actions, /Send Out Scout/, 'Send Out Scout action is missing.');
assert.match(actions, /key === 'M'/, 'Move Unit hotkey is missing.');
assert.match(actions, /key === 'X'/, 'Split Off Unit hotkey is missing.');
assert.match(actions, /key === 'C'/, 'Send Out Scout hotkey is missing.');
assert.match(actions, /key === 'F'/, 'Follow Ocean hotkey is missing.');
assert.match(actions, /follow-ocean/, 'Follow Ocean must be an explicit scouting action.');
assert.match(actions, /turnActionsArmFollowOcean/, 'Follow Ocean must be directly armable from the action bar.');
assert.match(actions, /\['O', 'OCEAN'\]\.includes\(terrain\)/, 'Follow Ocean must recognise both ocean terrain encodings.');
assert.match(actions, /turnActionsApplyFollowOcean/, 'Follow Ocean must resolve from the selected ocean edge.');
assert.match(actions, /item-icons\//, 'Action icons must use the Compendium image assets.');
assert.match(actions, /event\.key !== 'Shift'/, 'Shift release must be the chain commit boundary.');
assert.match(actions, /turnActionsCommit\(\)/, 'Turn actions must commit after a completed click/chain.');
assert.match(actions, /pendingMapClick/, 'Shift release must wait for the map click to finish appending its route.');
assert.match(actions, /await turnActionState\.pendingMapClick/, 'Shift release must await the pending map click before committing.');
assert.match(actions, /turnActionsPreviewHover/, 'Move Unit must calculate a route preview while hovering.');
assert.match(actions, /Keep the cost card anchored to the centre of the hex/, 'Hover feedback must stay stable while tracing within a hex.');
assert.match(actions, /turnActionsHoverAppendPreview/, 'Shift hover must preview the chained route.');
assert.match(actions, /movementPlannerFindAppendedRoute/, 'Shift-click must append a full route to a distant destination.');
assert.match(movementPlanner, /movementPlannerAppendRouteTo/, 'Movement planner must support multi-hex Shift appends.');
assert.match(actions, /turnActionsRefreshHover/, 'Changing Shift state must refresh the hover preview.');
assert.match(actions, /turnActionsUnitMovement/, 'Move Unit must use the selected unit movement profile.');
assert.match(actions, /turnActionsMovementRisk/, 'Move Unit must classify safe, risky and over-range routes.');
assert.match(actions, /Unit total:/, 'Move Unit must show the selected unit total movement.');
assert.match(actions, /Bad weather/, 'Move Unit must show the bad-weather movement warning.');
assert.match(actions, /turnActionsCancelRightClick/, 'Right-clicking during an active action must cancel it.');
assert.match(actions, /reset-scouting/, 'The action bar must provide a unit-scoped scouting reset.');
assert.match(actions, /open-scouts/, 'The action bar must open saved scout routes for the selected unit.');
assert.match(actions, /turnActionsOpenScoutRoutes/, 'Saved scout routes must support hover highlighting and edit/cancel actions.');
assert.match(actions, /if \(!dialog\.open\) dialog\.show\(\)/, 'Scouting routes must use a non-modal popup.');
assert.match(actions, /turnActionsBindDialogDrag/, 'Scouting routes popup must be draggable.');
assert.ok(!/turnActionsCloseScoutRoutes\(\);\s*await turnActionsEditSelectedScout/.test(actions), 'Editing a route must not close the route picker.');
assert.match(actions, /if \(dialog\.open\) turnActionsOpenScoutRoutes\(\)/, 'Cancelling a route must refresh the open route picker.');
assert.match(actions, /savedMovementResetMovementForUnit/, 'Movement reset must be scoped to the selected unit.');
assert.match(actions, /savedMovementResetScoutingForUnit/, 'Scouting reset must be scoped to the selected unit.');
assert.match(actions, /edit-scout/, 'A selected scout route must offer editing.');
assert.match(actions, /cancel-scout/, 'A selected scout route must offer cancellation.');
assert.match(actions, /title="Move Unit · M"/, 'Action buttons must expose their name and hotkey on hover.');
assert.match(actions, /title="Send Out Scout · C"/, 'Scout action must expose its name and hotkey on hover.');
assert.match(actions, /turnActionsBindTooltips/, 'Action controls must bind immediate custom tooltips.');
assert.match(renderer, /certainColor/, 'Route arrows must distinguish certain terrain from uncertain terrain.');
assert.match(renderer, /maybeColor/, 'Route arrows must expose a second colour for uncertain terrain.');
assert.match(renderer, /badWeatherAllowance/, 'Route arrows must account for movement lost to bad weather.');
assert.match(actions, /R\$\{savedMovementVisibleRouteNumber\(route\)\}/, 'Scouting routes must show route numbers.');
assert.match(actions, /editingRouteId/, 'Scout editing must update the existing route rather than insert a duplicate.');
assert.match(actions, /selectedScout \? turnActionsEditSelectedScout\(\) : turnActionsStart\('scout'\)/, 'C should edit a selected scout route and otherwise start scouting.');
assert.match(fs.readFileSync('src/saved-movement-plans.js', 'utf8'), /savedMovementHandleRouteLabelClick/, 'Scout labels must be clickable.');
assert.match(actions, /event\.button === 2/, 'Right-click handling must identify the secondary mouse button.');
assert.match(actions, /addEventListener\('mouseup', turnActionsCancelRightClick, true\)/, 'Right-click cancellation must run before map mouseup selection.');
assert.match(actions, /addEventListener\('contextmenu', turnActionsCancelRightClick, true\)/, 'Cancelled right-clicks must not open the browser context menu.');
assert.match(actions, /pendingOcean/, 'Scout coastal traces must retain the selected ocean tile.');
assert.match(actions, /orderForFeature/, 'Scout coastal traces must infer FOL/FOR.');
assert.match(savedPlans, /garrison.*fleet.*courier|fleet.*courier.*garrison/i, 'Garrisons, fleets and couriers must be handled as stationary units.');
assert.match(savedPlans, /plannedSplit && savedMovementUnitMove\(unit\.parentUnit\)/, 'A split created after parent movement must remain stationary.');
assert.match(savedPlans, /savedMovementIsStationaryUnit/, 'Stationary unit types must share one movement rule.');
assert.match(savedPlans, /removeAllScoutRoutesForUnit/, 'Changing a unit destination must clear its scouting routes.');
assert.match(savedPlans, /clearedScoutRoutes/, 'Movement commits must report cleared scouting routes.');
assert.match(savedPlans, /scoutCount\s*:\s*2/, 'Scouting must default to two people.');
assert.match(savedPlans, /scoutHorses\s*:\s*2/, 'Scouting must default to two horses.');
assert.ok(!actions.includes('Smart Scout') && !actions.includes('smartScout'), 'Smart Scout must be removed completely.');
assert.ok(!mapperStyles.includes('movement-planner-smart'), 'Smart Scout styling must be removed completely.');
assert.ok(!index.includes('movementPlannerCard') && !index.includes('plannerOverlayCard'), 'The old planning panel must not be present.');

console.log('Turn action UI regression tests passed');
