(() => {
  const X=window.TribeNetCompendiumExpansion; if(!X)return;
  const researchCard=window.TribeNetCompendiumResearchCard;
  const baseSkill=showSkill;
  showSkill=function(name,push=true){baseSkill(name,push);const s=skillByName(name);const article=$('compArticle');if(!s||!article)return;const rows=X.researchForSkill(s);const lead=article.querySelector('.comp-lead');if(s.validSkillsOnly&&lead)lead.insertAdjacentHTML('afterend','<div class="comp-callout warn"><strong>Valid Skills index only:</strong> this skill appears in the current Orders workbook, but the Mandate warns that not every Valid Skills entry is currently available as a normal Skill Attempt.</div>');if(s.researchUnlocked&&s.unlockResearch&&lead)lead.insertAdjacentHTML('afterend',`<div class="comp-callout research-unlock"><strong>Research-unlocked skill:</strong> ${esc(s.unlockResearch)}</div>`);if(rows.length){const refs=[...article.querySelectorAll('.comp-section')].find(x=>x.querySelector('h2')?.textContent==='Mandate references');const html=`<section class="comp-section compact-section"><div class="comp-inline-heading"><h2>Research topics</h2><span class="comp-muted">${rows.length} available</span></div><div class="comp-research-grid">${rows.map(researchCard).join('')}</div></section>`;if(refs)refs.insertAdjacentHTML('beforebegin',html);else article.insertAdjacentHTML('beforeend',html);}bindLinks(article);};

  function outputFor(row){for(const s of skills()){const r=(s.recipes||[]).find(x=>String(x.recipeKey||x.key||'')===String(row?.recipeKey||''));if(r?.outputItem)return r.outputItem;}return null;}
  const baseEntity=showEntity;
  showEntity=function(name,push=true){baseEntity(name,push);const e=entityByName(name),article=$('compArticle');if(!e||!article)return;
    if(e.validGoods){const m=e.validGoods,title=article.querySelector('.comp-title-row');if(title)title.insertAdjacentHTML('afterend',`<div class="comp-item-meta"><span><b>Orders table</b> ${esc(m.table||'—')}</span><span><b>Shortname</b> ${esc(m.shortname||'—')}</span><span><b>Weight</b> ${m.weight==null?'—':`${fmtNum(m.weight)} lb`}</span>${e.isImplement?'<span><b>Implement</b> Yes</span>':''}</div>`);}
    const used=[...article.querySelectorAll('.comp-section')].find(x=>x.querySelector('h2')?.textContent==='Used to make / operate');if(used)(e.consumers||[]).forEach((row,i)=>{const target=entityByName(outputFor(row));const strong=used.querySelectorAll('.comp-use')[i]?.querySelector('strong');if(strong&&target)strong.innerHTML=`<button class="comp-text-link" data-entity="${esc(target.key)}">${esc(row.name)}</button>`;});
    if((e.implementUses||[]).length){const all=e.implementUses,html=all.slice(0,80).map(u=>{const s=X.skillFind(u.activity);return `<span class="comp-use-chip">${s?`<button class="comp-text-link" data-skill="${esc(s.name)}">${esc(u.activity)}</button>`:esc(u.activity)}${u.item&&canon(u.item)!=='ALL'?` · ${esc(u.item)}`:''}</span>`;}).join('');article.insertAdjacentHTML('beforeend',`<section class="comp-section compact-section"><div class="comp-inline-heading"><h2>Used as an implement</h2><span class="comp-muted">${all.length} valid use${all.length===1?'':'s'}</span></div><div class="comp-tags">${html}</div></section>`);}
    if((e.researchTopics||[]).length){article.insertAdjacentHTML('beforeend',`<section class="comp-section compact-section"><div class="comp-inline-heading"><h2>Research</h2><span class="comp-muted">${e.researchTopics.length} linked topic${e.researchTopics.length===1?'':'s'}</span></div><div class="comp-research-grid">${e.researchTopics.map(researchCard).join('')}</div></section>`);}bindLinks(article);
  };

  const baseSearch=runSearch;runSearch=function(query){baseSearch(query);const q=canon(query);if(!q||compState.view.type!=='search')return;const matches=(X.research.topics||[]).filter(t=>canon(`${t.name} ${t.skill} ${t.benefit} ${t.preReq||''} ${t.recipe||''}`).includes(q));const host=$('compArticle')?.querySelector('.comp-search-results');if(!host||!matches.length)return;host.insertAdjacentHTML('beforeend',matches.map(t=>`<div class="comp-result" data-research="${esc(t.key)}"><strong>${esc(t.name)}</strong><span>Research · ${esc(t.skill)} · ${esc(t.benefit||'')}</span></div>`).join(''));bindLinks(host);};

  function install(){if(!compState.catalog)return setTimeout(install,25);X.addSkills();const view=clone(compState.view);renderNav();renderView(view,{push:false});}install();
})();
